# Generated by Django 3.1.4 on 2021-01-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectName', models.CharField(max_length=200, verbose_name='objectName')),
                ('detectedTime', models.DateTimeField(verbose_name='timestamp')),
            ],
        ),
    ]
